#!/usr/bin/env bash
# Mini-fleet gpu-gpu-shared lane runner (task spec: orchestration/state/tasks/
# 2026-08-27-minifleet.md §Components 3).
#
# Verbs:
#   start   — idempotently launch BOTH engine nodes on the P100 VM via ssh
#             (skips any node that is already up and healthy).
#   status  — report per-node health + VM hygiene (compute apps).
#   stop    — kill ONLY pids whose cmdline matches our exact run signature
#             "Qwen3.5-9B-Q4_K_M.*qwen-2node" and that we recorded in the
#             pidfile; NEVER touches residents (:8086 prod, :8090 upstream).
#
# VM hygiene contract (AC3): after stop, nvidia-smi compute apps must show
# ONLY {1620 upstream :8090, 2899 prod :8086} — no leftovers from this lane.
set -u

SSH_TARGET="${MINIFLEET_SSH_TARGET:-hydra-p100}"
RUN_DIR='~/qwen-2node'
PIDFILE="$RUN_DIR/pids"
# Exact run signature: model name + marker dir. kill -f patterns MUST stay this narrow.
RUN_SIGNATURE='Qwen3.5-9B-Q4_K_M.*qwen-2node'

log() { printf '[vm-run] %s\n' "$*"; }

# ── remote snippets ──────────────────────────────────────────────────────────

# Write the launcher script (idempotent upload; heredoc inside ssh).
upload_run_sh() {
  ssh "$SSH_TARGET" "mkdir -p $RUN_DIR && cat > $RUN_DIR/run.sh <<'EOS'
#!/usr/bin/env bash
# Generated by scripts/minifleet/vm-run.sh — do not hand-edit.
# Marker 'qwen-2node' in the cmdline is what makes our stop verb safe:
# pkill patterns are always anchored to BOTH the model file and this marker.
export LD_LIBRARY_PATH=\$HOME/hydra-min-test:\${LD_LIBRARY_PATH:-}
cd \$HOME/hydra-min-test
M=/mnt/kv_slots/Qwen3.5-9B-Q4_K_M.gguf
# qwen-2node marker is embedded via --alias (shows in every engine cmdline).
nohup ./llama-engine -m \$M --host 127.0.0.1 --port 8088 --rpc-port 9513 \\
  --n-gpu-layers 16 -t 3 -c 4096 --alias qwen-2node \\
  > \$HOME/qwen-2node/nodeA.log 2>&1 &
echo \$! > \$HOME/qwen-2node/nodeA.pid
nohup ./llama-engine -m \$M --host 127.0.0.1 --port 8089 --rpc-port 9514 \\
  --n-gpu-layers 8 -t 3 -c 4096 --alias qwen-2node \\
  > \$HOME/qwen-2node/nodeB.log 2>&1 &
echo \$! > \$HOME/qwen-2node/nodeB.pid
EOS
chmod +x $RUN_DIR/run.sh"
}

# List live ENGINE pids on the VM whose full cmdline matches the run signature.
# Only these are ever killable by this script.
# CRITICAL: pgrep -f also matches the transient `bash -c <cmdline-with-pattern>`
# ssh wrapper — filter it out (engine cmdlines never start with bash -c), and
# require the llama-engine binary in the cmdline too.
live_our_pids() {
  ssh "$SSH_TARGET" \
    "pgrep -af 'llama-engine.*$RUN_SIGNATURE' 2>/dev/null | grep -v 'bash -c' | awk '{print \$1}'" \
    || true
}

health_probe() {
  # Per-node: prints 'up' or 'down' given a port.
  ssh "$SSH_TARGET" "curl -s -m 3 http://127.0.0.1:\$1/health 2>/dev/null" >/dev/null 2>&1
}

node_state() {
  local port="$1"
  if ssh "$SSH_TARGET" "curl -sf -m 3 http://127.0.0.1:${port}/health 2>/dev/null | grep -q ok"; then
    echo up
  else
    echo down
  fi
}

# ── verbs ────────────────────────────────────────────────────────────────────

cmd_start() {
  log "target=$SSH_TARGET"
  upload_run_sh

  local a_state b_state
  a_state=$(node_state 8088)
  b_state=$(node_state 8089)

  if [ "$a_state" = up ] && [ "$b_state" = up ]; then
    log "both nodes already up — nothing to do (idempotent)"
    cmd_status
    return 0
  fi

  # Partial/crashed prior run: clear ONLY our own pids before relaunch.
  if [ "$a_state" = down ] || [ "$b_state" = down ]; then
    local stale
    stale=$(live_our_pids)
    if [ -n "$stale" ]; then
      log "stale nodes down but pids alive ($stale) — killing our pids only"
      ssh "$SSH_TARGET" "for p in $stale; do kill \$p 2>/dev/null; done; sleep 2"
    fi
  fi

  log "launching both nodes on VM"
  ssh "$SSH_TARGET" "bash $RUN_DIR/run.sh"

  # Wait for /health on both nodes (quirk #3): up to 180s.
  local deadline=$((SECONDS + 180)) state_a=down state_b=down
  while [ $SECONDS -lt $deadline ]; do
    state_a=$(node_state 8088)
    state_b=$(node_state 8089)
    [ "$state_a" = up ] && [ "$state_b" = up ] && break
    sleep 3
  done

  if [ "$state_a" != up ] || [ "$state_b" != up ]; then
    log "ERROR: nodes failed to become healthy (A=$state_a B=$state_b)"
    log "check ~/qwen-2node/node{A,B}.log on the VM"
    return 1
  fi

  log "both nodes healthy"
  ssh "$SSH_TARGET" "cat $RUN_DIR/nodeA.pid $RUN_DIR/nodeB.pid | tr '\\n' ' '; echo" \
    | awk '{print "[vm-run] pids:", $0}'
  cmd_status
}

cmd_status() {
  local a_state b_state
  a_state=$(node_state 8088)
  b_state=$(node_state 8089)
  log "nodeA :8088 = $a_state"
  log "nodeB :8089 = $b_state"
  log "compute apps on VM (must be ONLY {upstream :8090, prod :8086} + ours):"
  ssh "$SSH_TARGET" \
    "nvidia-smi --query-compute-apps=pid,used_memory --format=csv,noheader" \
    | sed 's/^/[vm-run]   /'
  log "our live pids (signature '$RUN_SIGNATURE'):"
  local ours
  ours=$(live_our_pids)
  if [ -n "$ours" ]; then
    printf '%s\n' "$ours" | sed 's/^/[vm-run]   /'
  else
    log "   (none)"
  fi
}

cmd_stop() {
  local ours
  ours=$(live_our_pids)
  if [ -z "$ours" ]; then
    log "no matching pids — already stopped"
  else
    log "stopping ONLY our pids: $(echo "$ours" | tr '\n' ' ')"
    # Two-phase: TERM (graceful slot teardown), then KILL only if still alive.
    ssh "$SSH_TARGET" "for p in $ours; do kill \$p 2>/dev/null; done"
    sleep 5
    local survivors
    survivors=$(live_our_pids)
    if [ -n "$survivors" ]; then
      log "survivors after TERM: $survivors — escalating to KILL"
      ssh "$SSH_TARGET" "for p in $survivors; do kill -9 \$p 2>/dev/null; done"
      sleep 2
    fi
  fi
  cmd_status
  # AC3 hygiene gate: fail loudly if anything beyond the two known residents
  # (:8090 upstream pid 1620, :8086 prod pid 2899) remains. This is advisory
  # for manual verification — this script NEVER touches unlisted pids.
  local foreign
  foreign=$(ssh "$SSH_TARGET" \
    "nvidia-smi --query-compute-apps=pid --format=csv,noheader" \
    | tr -d ' ' | grep -v -x -e 1620 -e 2899 -e '^[0-9]*$' -e '' || true)
  # After stop, ours should be gone; anything unaccounted is a hygiene violation.
  if [ -n "$foreign" ]; then
    log "WARNING: unexpected compute pids on VM: $foreign (verify manually — this script only ever touched: $ours)"
  else
    log "hygiene OK: only residents remain"
  fi
}

usage() {
  printf 'usage: %s {start|status|stop}\n' "$0" >&2
  exit 2
}

[ $# -eq 1 ] || usage
case "$1" in
  start)  cmd_start ;;
  status) cmd_status ;;
  stop)   cmd_stop ;;
  *)      usage ;;
esac
