#!/usr/bin/env python3
"""Fan canonical hydra_vortex commands + agent personas out to every provider.

Single source of truth:
  orchestration/commands/<name>.md   (slash commands)
  orchestration/agents/<name>.md     (agent personas)

Generated (DO NOT edit by hand — re-run this script):
  Commands -> .claude/commands/<n>.md
              .opencode/command/<n>.md
              .pi/prompts/<n>.md
  Agents   -> .claude/agents/<n>.md
              .opencode/agent/<n>.md
              .pi/skills/hydra-<n>/SKILL.md   (Agent Skills standard)

Run from the repo root:  python3 orchestration/scripts/sync-agents.py
"""
from __future__ import annotations
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
HOME = pathlib.Path.home()
GEN_BANNER = "<!-- GENERATED by orchestration/scripts/sync-agents.py — edit the canonical file in orchestration/, then re-run. -->\n"

# Output roots per scope. Project = this repo; global = system-wide (all workspaces).
GLOBAL = "--global" in sys.argv or "-g" in sys.argv

# Stable, cwd-independent home for the orchestration scaffold when installed globally.
ORCH_HOME = HOME / "agents-orchestration"
# String that "orchestration/" references are rewritten to in generated files.
# Project scope keeps the cwd-relative path; global scope pins the absolute path.
ORCH_REF = f"{ORCH_HOME}/" if GLOBAL else "orchestration/"

if GLOBAL:
    CLAUDE_CMD = HOME / ".claude" / "commands"
    CLAUDE_AGENT = HOME / ".claude" / "agents"
    OC_CMD = HOME / ".config" / "opencode" / "command"
    OC_AGENT = HOME / ".config" / "opencode" / "agent"
    PI_PROMPT = HOME / ".pi" / "agent" / "prompts"
    PI_SKILL = HOME / ".pi" / "agent" / "skills"
else:
    CLAUDE_CMD = ROOT / ".claude" / "commands"
    CLAUDE_AGENT = ROOT / ".claude" / "agents"
    OC_CMD = ROOT / ".opencode" / "command"
    OC_AGENT = ROOT / ".opencode" / "agent"
    PI_PROMPT = ROOT / ".pi" / "prompts"
    PI_SKILL = ROOT / ".pi" / "skills"


def repath(text: str) -> str:
    """Rewrite cwd-relative 'orchestration/' refs to the active scope's path."""
    if ORCH_REF == "orchestration/":
        return text
    return text.replace("orchestration/", ORCH_REF)


def parse(md: str) -> tuple[dict, str]:
    """Return (frontmatter dict, body). Simple key: value YAML only."""
    if not md.startswith("---"):
        return {}, md
    _, fm, body = md.split("---", 2)
    meta: dict[str, str] = {}
    for line in fm.strip().splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    return meta, body.lstrip("\n")


def fm_block(pairs: list[tuple[str, str]]) -> str:
    lines = ["---"]
    for k, v in pairs:
        if v is not None and v != "":
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def rel(path: pathlib.Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote {rel(path)}")


def sync_commands() -> None:
    src = ROOT / "orchestration" / "commands"
    if not src.is_dir():
        return
    print("commands:")
    for f in sorted(src.glob("*.md")):
        meta, body = parse(f.read_text())
        name = f.stem
        desc = repath(meta.get("description", ""))
        hint = meta.get("argument-hint", "")
        tools = meta.get("allowed-tools", "")
        base = repath(GEN_BANNER + "\n" + body)

        # Claude Code
        write(CLAUDE_CMD / f"{name}.md",
              fm_block([("description", desc), ("argument-hint", hint),
                        ("disable-model-invocation", "true"),
                        ("allowed-tools", tools)]) + base)
        # opencode
        write(OC_CMD / f"{name}.md",
              fm_block([("description", desc), ("agent", "build")]) + base)
        # pi
        write(PI_PROMPT / f"{name}.md",
              fm_block([("description", desc)]) + base)


def sync_agents() -> None:
    src = ROOT / "orchestration" / "agents"
    if not src.is_dir():
        return
    print("agents:")
    for f in sorted(src.glob("*.md")):
        meta, body = parse(f.read_text())
        name = meta.get("name", f.stem)
        desc = repath(meta.get("description", ""))
        mode = meta.get("mode", "subagent")
        perm = meta.get("permission", "")
        base = repath(GEN_BANNER + "\n" + body)

        # Claude Code subagent (model omitted -> inherits session/spawn model)
        write(CLAUDE_AGENT / f"{name}.md",
              fm_block([("name", name), ("description", desc)]) + base)
        # opencode agent (permission passed through when set on the canonical file)
        write(OC_AGENT / f"{name}.md",
              fm_block([("description", desc), ("mode", mode),
                        ("permission", perm)]) + base)
        # pi has no native agent file -> ship persona as an Agent Skill
        write(PI_SKILL / f"hydra-{name}" / "SKILL.md",
              fm_block([("name", f"hydra-{name}"), ("description", desc)]) + base)


def seed_global_scaffold() -> None:
    """Copy the canonical orchestration scaffold to the stable global home.

    Read-only source of truth (charters, providers.yaml, agents, commands,
    scripts) is mirrored to ~/agents-orchestration so globally-installed
    commands resolve their paths from any cwd. The mutable state/ dir is
    created but never overwritten.
    """
    import shutil

    src = ROOT / "orchestration"
    print(f"scaffold: seeding {ORCH_HOME}")
    ORCH_HOME.mkdir(parents=True, exist_ok=True)
    for item in ["GOALS.md", "ARCHITECTURE.md", "LEAD_CHARTER.md",
                 "MONITOR_CHARTER.md", "QUOTA.md", "README.md",
                 "providers.yaml"]:
        s = src / item
        if s.is_file():
            shutil.copy2(s, ORCH_HOME / item)
    for d in ["agents", "commands", "scripts"]:
        s = src / d
        if s.is_dir():
            shutil.copytree(s, ORCH_HOME / d, dirs_exist_ok=True)
    (ORCH_HOME / "state").mkdir(exist_ok=True)
    (ORCH_HOME / "state" / ".gitkeep").touch()
    print(f"  seeded {ORCH_HOME}")


def main() -> int:
    print(f"root: {ROOT}")
    print(f"scope: {'GLOBAL (system-wide)' if GLOBAL else 'project-local'}")
    if GLOBAL:
        print(f"orch home: {ORCH_HOME}")
        seed_global_scaffold()
    sync_commands()
    sync_agents()
    print("done. Restart each agent tool to pick up new files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
