[uwsgi]
chdir = /usr/local/searxng
module = searx.webapp
uid = 1000
gid = 1000
socket = 0.0.0.0:8088
master = true
processes = 1
threads = 4
die-on-term = true
cheaper = 1
cheaper-initial = 1
cheaper-step = 1
cheaper-overload = 1
cheaper-idle = 300
lazy-apps = true
vacuum = true
die-on-exception = true
hook-master-start = syscommand: umask 000
hook-master-start = syscommand: mkdir -p /tmp/searxng
hook-master-start = syscommand: chmod 777 /tmp/searxng