name: Debug RT Gating

on:
  workflow_dispatch:
    inputs:
      run-tests:
        required: false
        default: "none"
        type: string

jobs:
  plain:
    runs-on: ubuntu-latest
    steps:
      - run: echo "inputs.run-tests=[${{ inputs.run-tests }}] gei=[${{ github.event.inputs.run-tests }}]"

  uses-gated-inputs:
    name: uses-gated-inputs
    if: inputs.run-tests == 'system'
    uses: ./.github/workflows/debug-reusable.yml

  uses-gated-gei:
    name: uses-gated-gei
    if: github.event.inputs.run-tests == 'system'
    uses: ./.github/workflows/debug-reusable.yml

  uses-with-inputs:
    name: uses-with-inputs
    uses: ./.github/workflows/debug-reusable.yml
    with:
      value: ${{ inputs.run-tests }}

  uses-with-gei:
    name: uses-with-gei
    uses: ./.github/workflows/debug-reusable.yml
    with:
      value: ${{ github.event.inputs.run-tests }}
