name: Diag Reusable

on:
  workflow_call:
    inputs:
      value:
        required: false
        default: "none"
        type: string

jobs:
  show:
    runs-on: ubuntu-latest
    if: ${{ inputs.value == 'system' }}
    steps:
      - run: |
          echo "GATED-ON received value = [${{ inputs.value }}]"
